-- Data awal Website FBKK Jember
-- Jalankan setelah schema.sql: mysql -u root -p fbkk_db < database/seed.sql

USE fbkk_db;

-- Akun demo (password: admin123 / demo123)
INSERT INTO users (username, password, role, is_verified) VALUES
('disnaker', 'scrypt:32768:8:1$6FO4sQssUJbMykIF$4c0770aba08d401e1e1ea0c6ffe3d6d7aeb131962ede350837000401c0f9ce82fe7d56e125c850a86cd92564199911181c7d0a80fbc5ccbbebfb6fa9fe3b1946', 'disnaker', 1),
('smk_demo', 'scrypt:32768:8:1$KU7yl1yoZ2FsEJ3j$adbb8eb84cae0cc6c34bd4b33ccec86bea7efb18ee67e52c55450e7a3c4d97481a9c063a0b6fc0e8b078d6cdacf51aeffe82a3edc621316df081f6c56e6aa027', 'fbkk', 1),
('user_baru', 'scrypt:32768:8:1$KU7yl1yoZ2FsEJ3j$adbb8eb84cae0cc6c34bd4b33ccec86bea7efb18ee67e52c55450e7a3c4d97481a9c063a0b6fc0e8b078d6cdacf51aeffe82a3edc621316df081f6c56e6aa027', 'fbkk', 0);

-- Daftar sekolah anggota FBKK (176 sekolah)
INSERT INTO anggota_fbkk (id_user, sekolah, alamat, kecamatan, status) VALUES
(NULL, 'SMKS AL - KHOLILY', 'JL. A. YANI NO.05 MLOKOREJO - PUGER RT 4 RW 2 Mlokorejo Kode Pos 68164', 'Puger', 'Swasta'),
(NULL, 'SMKS PLUS NURUZ ZAMAN', 'JL. MAKAM MRONGGI RT 3 RW 3 Mrawan Kode Pos 68182', 'Mayang', 'Swasta'),
(NULL, 'SMKS DARUN NAJAH', 'JL. H. MOCH.NOER RT 5 RW 2 Rowo Indah Kode Pos 68175', 'Ajung', 'Swasta'),
(NULL, 'SMK NURUL YAQIN', 'Jl. Gumuk Gebang RT RW Nogosari Kode Pos', 'Rambipuji', 'Swasta'),
(NULL, 'SMKS DARUL HUDA', 'KOTA BLATER GANG MANGGA NO. 10 RT 1 RW 3 Andongsari Kode Pos 68172', 'Ambulu', 'Swasta'),
(NULL, 'SMKS ISLAM TERPADU IBNU KATSIR', 'JL. WISATA REMBANGAN KM. 7 RT 2 RW 7 Kemuningllor Kode Pos 68191', 'Arjasa', 'Swasta'),
(NULL, 'SMKS 09 MA`ARIF NU', 'Jl. Sultan Agung No. 169 RT 1 RW 4 Rowo Tengah Kode Pos 68156', 'Sumberbaru', 'Swasta'),
(NULL, 'SMKS PGRI 2 JEMBER', 'Jl. KURMA ( Belakang Kantor Pos Patrang ) Jember RT 0 RW 0 Patrang Kode Pos 68111', 'Patrang', 'Swasta'),
(NULL, 'SMKS DARUL MUKHLISIN', 'JL KH ABDUL AZIZ NO 1 Tegalan, Sumber Kejayan, Mayang, Jember, Jawa Timur RT 3 RW 4 Sumber Kejayan Kode Pos 68182', 'Mayang', 'Swasta'),
(NULL, 'SMKS MODAL BANGSA', 'JLN. CURAH SUKO RAYA NO.18 - RAMBIPUJI RT 1 RW 1 Kaliwining Kode Pos 68152', 'Rambipuji', 'Swasta'),
(NULL, 'SMKS MADINATUL ULUM', 'JL. TEMPUREJO RT 0 RW 0 Cangkring Kode Pos 68171', 'Jenggawah', 'Swasta'),
(NULL, 'SMKN 7 JEMBER', 'JL. PB. SUDIRMAN NO.16 RT 1 RW 2 Jatiroto Kode Pos 68156', 'Sumberbaru', 'Negeri'),
(NULL, 'SMKN 8 JEMBER', 'JL. PELITA NO.27 RT 0 RW 0 Sidomekar Kode Pos 68157', 'Semboro', 'Negeri'),
(NULL, 'SMKS MAARIF BANGSALSARI', 'Jl. Balung No. 114 RT 1 RW 5 Sukorejo Kode Pos 68154', 'Bangsalsari', 'Swasta'),
(NULL, 'SMKN 5 JEMBER', 'JL. BRAWIJAYA NO. 55 JEMBER RT 2 RW 1 Jubung Kode Pos 68151', 'Sukorambi', 'Negeri'),
(NULL, 'SMKS BANY KHOLIEL', 'Jl. Balung No.99 Kedungsuko Kec. Bangsalsari RT 3 RW 27 Bangsalsari Kode Pos 68154', 'Bangsalsari', 'Swasta'),
(NULL, 'SMKS MAARIF TERPADU TEMPUREJO', 'JL. LETJEN. SUPRIYADI NO.001 CURAHTAKIR RT 17 RW 4 Curahtakir Kode Pos 68173', 'Tempurejo', 'Swasta'),
(NULL, 'SMKS RAUDLATUL AKBAR', 'JL. BASUKI RAHMAT NO.58 TEGAL BESAR - KALIWATES RT 1 RW 1 Tegal Besar Kode Pos 68132', 'Kaliwates', 'Swasta'),
(NULL, 'SMKS ASH - SHIDDIQI', 'JL DUSUN KRAJAN KIDUL DESA CURAHLELE RT 4 RW 1 Curahlele Kode Pos 68161', 'Balung', 'Swasta'),
(NULL, 'SMKS PLUS BUSTANUL MAARIF', 'JL. PANJAITAN NO. 56 RT 2 RW 2 Gumukmas Kode Pos 68165', 'Gumuk Mas', 'Swasta'),
(NULL, 'SMKS 02 ISLAM 45 AMBULU', 'JL. WATU ULO 82 AMBULU RT 3 RW 5 Tegalsari Kode Pos 68172', 'Ambulu', 'Swasta'),
(NULL, 'SMKN 3 JEMBER', 'Jl. Dr. Soebandi No. 31 RT 0 RW 0 Jember Lor Kode Pos 68118', 'Patrang', 'Negeri'),
(NULL, 'SMKS MUHAMMADIYAH JEMBER', 'JL. PB. SUDIRMAN NO.I/31 Jember Lor Patrang Jember RT 0 RW 0 Jember Lor Kode Pos 68118', 'Patrang', 'Swasta'),
(NULL, 'SMKS KERTONEGORO', 'Jl. Nusa Indah No. 128 Desa Kertonegoro Kec. Jenggawah RT RW Kertonegoro Kode Pos 68171', 'Jenggawah', 'Swasta'),
(NULL, 'SMKS AL BADRI KALISAT', 'JL. ARJASA KALISAT NO.50 GUMUKSARI RT 2 RW 1 Gumuksari Kode Pos 68193', 'Kalisat', 'Swasta'),
(NULL, 'SMKS SUNAN DRAJAT', 'JL. SUNAN DRAJAT NO. 09 SUMURAN RT 2 RW 2 Klompangan Kode Pos 68175', 'Ajung', 'Swasta'),
(NULL, 'SMKS AL AMIEN', 'JL K. MASDUQI RT 3 RW 3 Sabrang Kode Pos 68172', 'Ambulu', 'Swasta'),
(NULL, 'SMKS AL IKHLASH', 'JL PEMUDA 31 GUDANG KARANG RT 3 RW 29 Rambipuji Kode Pos 68152', 'Rambipuji', 'Swasta'),
(NULL, 'SMKS NURUL MARIFAH', 'JL SEMPOLAN NO 18 RT 0 RW 0 Plalangan Kode Pos 68193', 'Kalisat', 'Swasta'),
(NULL, 'SMKS RAUDLATUL ULUM', 'Desa Suren Kecamatan Ledokombo RT 2 RW 3 Suren Kode Pos 68196', 'Ledok Ombo', 'Swasta'),
(NULL, 'SMKS AL IMAM', 'JL.JAMBUAN RT.10 RW.04 DESA GAMBIRAN KEC.KALISAT RT 1 RW 1 Gambiran Kode Pos 68193', 'Kalisat', 'Swasta'),
(NULL, 'SMKS BASTREN NURUSSALAM', 'JL IMAM SYAFI I NO. 07 RT 2 RW 7 Sumberrejo Kode Pos 68172', 'Ambulu', 'Swasta'),
(NULL, 'SMKS NAHDLATUTH THALABAH WULUHAN', 'JL. K.H. IMAM BUKHORI RT 4 RW 1 Kesilir Kode Pos 68162', 'Wuluhan', 'Swasta'),
(NULL, 'SMKS KESEHATAN MEDIKA FARMA', 'JL. PB SUDIRMAN NO 25 AJUNG KALISAT RT 2 RW 11 Kalisat Kode Pos 68193', 'Kalisat', 'Swasta'),
(NULL, 'SMKS ZAIDUL ALI SUKOWONO', 'JL. STASIUN SUKOSARI - SUKOREJO RT 2 RW 2 Sukorejo Kode Pos 68194', 'Sukowono', 'Swasta'),
(NULL, 'SMKS TERPADU SYAHID', 'JL. PROTOKOL DESA DSN MANGGIS RT : 02 RW : II RT 0 RW 0 Sukorambi Kode Pos 68151', 'Sukorambi', 'Swasta'),
(NULL, 'SMKS DARUSSALAM', 'JL. GATOT SUBROTO NO.68 RT 2 RW 15 Jombang Kode Pos 68168', 'Jombang', 'Swasta'),
(NULL, 'SMKS BERDIKARI JEMBER', 'Jl. Jambu No.05 RT 0 RW 0 Patrang Kode Pos 68111', 'Patrang', 'Swasta'),
(NULL, 'SMKS DARUSSALAM', 'JL BRAWIJAYA NO. 10 RT 38 RW 10 Pontang Kode Pos 68172', 'Ambulu', 'Swasta'),
(NULL, 'SMKS NURUL MUKMIN', 'JL. PTPN XII GUNUNG GAMBIR RT 2 RW 14 Jatiroto Kode Pos 68156', 'Sumberbaru', 'Swasta'),
(NULL, 'SMKS WALISONGO RAMBIPUJI', 'JL. ARGOPURO NO. 83 RT 2 RW 19 RAMBIGUNDAM Kode Pos 68152', 'Rambipuji', 'Swasta'),
(NULL, 'SMKS ISLAM YANABIUL ULUM', 'JL GAMBIRAN NO 01 DS PLALANGAN RT 1 RW 19 Plalangan Kode Pos 68193', 'Kalisat', 'Swasta'),
(NULL, 'SMKS MANDALA', 'JL. SUMATRA 118 -120 RT 4 RW 6 Sumbersari Kode Pos 68121', 'Sumbersari', 'Swasta'),
(NULL, 'SMKS ISLAM AL AZHAR LEDOKOMBO', 'DUSUN KARANG BIREH RT 1 RW 9 Sumber Lesung Kode Pos 68196', 'Ledok Ombo', 'Swasta'),
(NULL, 'SMKS 4 PANCASILA AMBULU', 'JL RAYA SUYITMAN NO 31 RT 3 RW 15 Ambulu Kode Pos 68172', 'Ambulu', 'Swasta'),
(NULL, 'SMKS SHOFA MARWA', 'JL KALISAT RT 1 RW 2 Patemon Kode Pos 68191', 'Pakusari', 'Swasta'),
(NULL, 'SMKS NURUL MANNAN', 'JL PASAR JUMAT NO 2 RT 1 RW 2 Sukogidri Kode Pos 68196', 'Ledok Ombo', 'Swasta'),
(NULL, 'SMKS FATIHUL ULUM', 'JL. RAYA JEMBER KLATAKAN TANGGUL JEMBER RT 2 RW 14 Klatakan Kode Pos 68155', 'Tanggul', 'Swasta'),
(NULL, 'SMKS MIFTAHUL ULUM', 'Jl. KH. UMAR No. 21 RT 1 RW 1 Sumber Kalong Kode Pos 68193', 'Kalisat', 'Swasta'),
(NULL, 'SMKS 2 PANCASILA', 'JL. LUMBA-LUMBA NO. 9 RT 1 RW 1 Sempusari Kode Pos 68135', 'Kaliwates', 'Swasta'),
(NULL, 'SMKS DARUS SHOLIHIN PUGER', 'JL. Makam Roudlotul Jannah Puger Kulon RT 2 RW 4 Puger Kulon Kode Pos 68164', 'Puger', 'Swasta'),
(NULL, 'SMKS PERIKANAN DAN KELAUTAN', 'JL. A. YANI RT 0 RW 0 Puger Kulon Kode Pos 68164', 'Puger', 'Swasta'),
(NULL, 'SMKS BAHJATUL ULUM', 'JL. KALISAT SUKOWONO RT 6 RW 3 Sukowono Kode Pos 68194', 'Sukowono', 'Swasta'),
(NULL, 'SMKS NURIS JEMBER', 'JL. PANGANDARAN 48 RT 2 RW 1 Antirogo Kode Pos 68125', 'Sumbersari', 'Swasta'),
(NULL, 'SMKS MABDAUL MAARIF', 'JL. KH. A. WAHID HASYIM No. 30 RT 1 RW 26 Jombang Kode Pos 68168', 'Jombang', 'Swasta'),
(NULL, 'SMKS MINQU', 'JL. MAYANGAN NO. 03 RT 3 RW 10 Gumukmas Kode Pos 68165', 'Gumuk Mas', 'Swasta'),
(NULL, 'SMKS 1 PANCASILA AMBULU', 'JL. RONGGOLAWE NO.05 RT 2 RW 22 Ambulu Kode Pos 68172', 'Ambulu', 'Swasta'),
(NULL, 'SMKS KARTINI JEMBER', 'JL. LETJEN SUTOYO NO. 30 RT 2 RW 32 Kebonsari Kode Pos 68122', 'Sumbersari', 'Swasta'),
(NULL, 'SMKS AS SALAFI BALUNG', 'JL. PESANTREN KRAJAN BALUNG KIDUL RT 2 RW 2 Balung Kidul Kode Pos 68161', 'Balung', 'Swasta'),
(NULL, 'SMKS SUNAN GIRI', 'DSN. GUDANG DUREN SUBO - PAKUSARI RT 4 RW 2 Subo Kode Pos 68181', 'Pakusari', 'Swasta'),
(NULL, 'SMKS KESEHATAN BINA MITRA HUSADA', 'JALAN RS PRAWIRO DIRJO NO 1A RT 2 RW 5 Wirowongso Kode Pos 68175', 'Ajung', 'Swasta'),
(NULL, 'SMKS KESEHATAN TPA JEMBER', 'JL. BRANJANGAN NO.01 BINTORO RT 2 RW 4 Bintoro Kode Pos 68113', 'Patrang', 'Swasta'),
(NULL, 'SMKS AL MUNAWAROH', 'JL. MOJOPAHIT II NO.139 KRATON WONOASRI RT 1 RW 2 Tempurejo Kode Pos 68173', 'Tempurejo', 'Swasta'),
(NULL, 'SMKS AL QODIRI GUMUKMAS', 'JL. UMBULSARI NO. 39 RT 2 RW 17 Gumukmas Kode Pos 68165', 'Gumuk Mas', 'Swasta'),
(NULL, 'SMKS MOCH SROEDJI JEMBER', 'JL. SRIWIJAYA NO. 32 JEMBER RT 2 RW 2 Karangrejo Kode Pos 68124', 'Sumbersari', 'Swasta'),
(NULL, 'SMKS SPBMA YAPENI 01 JEMBER', 'JL. SLAMET RIYADI 64 JEMBER RT 4 RW 5 Patrang Kode Pos 68111', 'Patrang', 'Swasta'),
(NULL, 'SMKS AL QURNAINI', 'Dsn. Karang Semanding RT.01 RW.08 RT 1 RW 8 Sukorejo Kode Pos 68154', 'Bangsalsari', 'Swasta'),
(NULL, 'SMKS DARUL ULUM GUMUKMAS', 'JL. GARUDA NO.77 GUMUKMAS RT 4 RW 7 Karangrejo Kode Pos 68165', 'Gumuk Mas', 'Swasta'),
(NULL, 'SMKS SUNAN AMPEL', 'MUJAHER NO.03 SUKORAMBI RT 1 RW 4 Sukorambi Kode Pos 68151', 'Sukorambi', 'Swasta'),
(NULL, 'SMKS AR RAUDLAH', 'Dusun Gendir RT 1 RW 2 Karangpring Kode Pos 68151', 'Sukorambi', 'Swasta'),
(NULL, 'SMKS NURUS SHOLAH', 'JL. MOJOGEMI Jelbuk Jember RT 2 RW 4 Sukowiryo Kode Pos 68192', 'Jelbuk', 'Swasta'),
(NULL, 'SMKS FARMASI JEMBER', 'JL. PANGANDARAN NO.42 RT.03 RW 02 SUMBERSARI JEMBER RT 2 RW 2 Antirogo Kode Pos 68125', 'Sumbersari', 'Swasta'),
(NULL, 'SMKS BAITUL HIKMAH', 'JL. CUT NYADIN 2 RT 1 RW 2 Tempurejo Kode Pos 68173', 'Tempurejo', 'Swasta'),
(NULL, 'SMKS SUNAN GIRI', 'JL. KH. ABDUL AZIZ NO.78 - BALUNG RT 2 RW 16 Curahlele Kode Pos 68161', 'Balung', 'Swasta'),
(NULL, 'SMKS AL BUKHORI', 'Jalan KH. Abdul Karim, 19 RT 5 RW 12 Kesilir Kode Pos 68162', 'Wuluhan', 'Swasta'),
(NULL, 'SMKS INKLUSI - TPA JEMBER', 'JL. BRANJANGAN NO.01 BINTORO RT 0 RW 0 Bintoro Kode Pos 68113', 'Patrang', 'Swasta'),
(NULL, 'SMKS AL KAMIL SIROJUL ANWAR', 'JL Kyai Haji Sirojuddin Ilyas No.04 RT 1 RW 1 Pecoro Kode Pos 68152', 'Rambipuji', 'Swasta'),
(NULL, 'SMKS MAHFILUD DUROR II', 'JALAN. BONDOWOSO NO. 17 SUGER KIDUL RT 1 RW 1 Suger Kidul Kode Pos 68192', 'Jelbuk', 'Swasta'),
(NULL, 'SMKS MUHAMMADIYAH 3 AMBULU', 'JL. CANDRADIMUKA NO. 06 RT 1 RW 17 Ambulu Kode Pos 68172', 'Ambulu', 'Swasta'),
(NULL, 'SMKS 3 PANCASILA AMBULU', 'KOPRAL SUTOMO NO.266 RT 1 RW 2 Karang Anyar Kode Pos 68172', 'Ambulu', 'Swasta'),
(NULL, 'SMKS AL-AZHAR', 'JL. ARGOPURO N0.99 RT 2 RW 3 Tisnogambar Kode Pos 68154', 'Bangsalsari', 'Swasta'),
(2, 'SMKN 1 JEMBER', 'JL. JAMBU NO. 17 RT 1 RW 1 Patrang Kode Pos 68111', 'Patrang', 'Negeri'),
(NULL, 'SMK ISLAM AR-RAUDLAH', 'Jl. Wali Songo No. 05 Sukosari RT 7 RW 5 Jatisari Kode Pos 68171', 'Jenggawah', 'Swasta'),
(NULL, 'SMKS NURUL ANWAR SILO', 'JL. KH. DEWANTARA NO.02 SEMPOLAN RT 2 RW 1 Sempolan Kode Pos 68184', 'Silo', 'Swasta'),
(NULL, 'SMKS ISLAM AL - MURSYIDIYAH', 'JL. KH. SIROJUDDIN 04, LEDOK, SIDOMUKTI RT 0 RW 0 Sidomukti Kode Pos 68182', 'Mayang', 'Swasta'),
(NULL, 'SMKS YP 17 JOMBANG JEMBER', 'JL. Ki Hajar Dewantoro Jombang - Jember RT 1 RW 9 Jombang Kode Pos 68168', 'Jombang', 'Swasta'),
(NULL, 'SMKS AL MUTTAQIN', 'JL. SRITI NO. 128 RT 2 RW 9 Banjar Sengon Kode Pos 68115', 'Patrang', 'Swasta'),
(NULL, 'SMKS RIYADLUS SHOLIHIEN', 'JL. MELATI V/10 JEMBER KIDUL RT 5 RW 23 Jember Kidul Kode Pos 68131', 'Kaliwates', 'Swasta'),
(NULL, 'SMKS FULL DAY BUSTANUL ULUM', 'JL. PP. BULUGADING NO,125 LANGKAP RT 2 RW 8 Langkap Kode Pos 68154', 'Bangsalsari', 'Swasta'),
(NULL, 'SMKS MIFTAHUL HUDA', 'JL. PTPN V11 GUNUNG GAMBIR RT 2 RW 4 Jatiroto Kode Pos 68156', 'Sumberbaru', 'Swasta'),
(NULL, 'SMKS LATIFIYAH', 'JALAN KH ABDUL LATIF 40 RT 6 RW 6 Glagahwero Kode Pos 68193', 'Kalisat', 'Swasta'),
(NULL, 'SMKS PLUS NURUL ULUM PANTI', 'JL. RAJAWALI NO.110 Desa Kemuningsari Lor Kecamatan Panti Kabupaten Jember RT 5 RW 4 Kemuningsari Lor Kode Pos 68153', 'Panti', 'Swasta'),
(NULL, 'SMKS ISLAM AL IMAM', 'JL. GUMUKSRAYU NO.1 CUMEDAK SUMBERJAMBE RT 1 RW 2 CUMEDAK Kode Pos 68195', 'Sumberjambe', 'Swasta'),
(NULL, 'SMKS MAARIF NU GUMUKMAS', 'JALAN KH HASYIM ASY ARI NO 13 RT 3 RW 2 Kepanjen Kode Pos 68165', 'Gumuk Mas', 'Swasta'),
(NULL, 'SMKS NURUL HIKMAH', 'RAYA PUGER NO.63 RT 0 RW 0 Kasiyan Timur Kode Pos 68164', 'Puger', 'Swasta'),
(NULL, 'SMKN 4 JEMBER', 'JL. KARTINI NO. 1 RT 1 RW 1 Patrang Kode Pos 68118', 'Patrang', 'Negeri'),
(NULL, 'SMKS 01 DIPONEGORO WULUHAN', 'JL. PAHLAWAN NO. 186, PURWOJATI RT 1 RW 17 Dukuh Dempok Kode Pos 68162', 'Wuluhan', 'Swasta'),
(NULL, 'SMKS ISLAM BUSTANUL ULUM', 'JL. HIMALAYA NO.17 PAKUSARI RT 0 RW 0 Pakusari Kode Pos 68181', 'Pakusari', 'Swasta'),
(NULL, 'SMKS NURUL MUKMININ SUKOWONO', 'JALAN IMAM SUKARTO RT 0 RW 0 Balet Baru Kode Pos 68194', 'Sukowono', 'Swasta'),
(NULL, 'SMKS ASY - SYAFAAH', 'JL. JEND. BASUKI RAHMAT V/31 KEBONSARI RT 6 RW 31 KEBONSARI Kode Pos 68123', 'Sumbersari', 'Swasta'),
(NULL, 'SMKS MAMBAUL ULUM', 'JL. KH. WAHID HASYIM RT 1 RW 1 Sukowono Kode Pos 68194', 'Sukowono', 'Swasta'),
(NULL, 'SMK PERIKANAN PERTANIAN TERPADU PUGER', 'Jl. KH. Toyyib No. 5 RT 2 RW 2 Mojomulyo Kode Pos 68164', 'Puger', 'Swasta'),
(NULL, 'SMKS ZAINUL HASAN', 'JL. PERJUANGAN NO.10 BALUNG LOR RT 0 RW 0 Balung Lor Kode Pos 68161', 'Balung', 'Swasta'),
(NULL, 'SMKS NURUL ISLAM', 'JL KH BASUNI RT 1 RW 0 Sempolan Kode Pos 68183', 'Silo', 'Swasta'),
(NULL, 'SMKS DARUL HIKMAH', 'JL. YOS SUDARSO 114 KRANJINGAN RT 1 RW 19 Keranjingan Kode Pos 68123', 'Sumbersari', 'Swasta'),
(NULL, 'SMKS AL ISHLAH', 'JL. RAUNG NO.103 MAYANG - JEMBER RT 2 RW 17 Mayang Kode Pos 68182', 'Mayang', 'Swasta'),
(NULL, 'SMKS MIFTAHUL WARITSIN', 'JL. KM. JAHURI 39 RT 2 RW 4 Sukosari Kode Pos 68194', 'Sukowono', 'Swasta'),
(NULL, 'SMKS RAUDLOTUL ATHFAL', 'DSN. JERENG DS. GUGUT RT 1 RW 3 GUGUT Kode Pos 68152', 'Rambipuji', 'Swasta'),
(NULL, 'SMKS AHMAD YANI BANGSALSARI', 'JL. RAYA A. YANI NO. 2A RT 1 RW 11 Bangsalsari Kode Pos 68154', 'Bangsalsari', 'Swasta'),
(NULL, 'SMKS ZAINUL MUIN KALISAT', 'JL. KH. ZAINUL KALISAT RT 4 RW 15 Kalisat Kode Pos 68193', 'Kalisat', 'Swasta'),
(NULL, 'SMKS MIFTAHUL MUBTADIIN', 'DUSUN GONDOSARI RT 01 RW 10 RT 1 RW 10 Rowo Tengah Kode Pos 68156', 'Sumberbaru', 'Swasta'),
(NULL, 'SMK RAUDLATUL ULUM', 'Jl. A Yani No.5 Dusun Gaplek RT 1 RW 3 Suci Kode Pos 68153', 'Panti', 'Swasta'),
(NULL, 'SMKS SUNAN GIRI', 'JL PASAR MANYUK KRAJAN RT 1 RW 1 Mojomulyo Kode Pos 68164', 'Puger', 'Swasta'),
(NULL, 'SMK TAHFIDZUL QUR`AN', 'Jln. Raya Kasiyan Rt.16/Rw.01 Dusun Krajan Lor RT RW Paleran Kode Pos', 'Umbulsari', 'Swasta'),
(NULL, 'SMKS NURIS HIDAYAT', 'JL BANDEALIT NO 55 RT 2 RW 9 Curahnongko Kode Pos 68173', 'Tempurejo', 'Swasta'),
(NULL, 'SMKS ASRAMA PEMBINA MASYARAKAT', 'Jl. KH. Abdul Hamid Gang IV No. 28-30 Kec. Jenggawah Kab. Jember RT 10 RW 2 Jatimulyo Kode Pos 68171', 'Jenggawah', 'Swasta'),
(NULL, 'SMKS TRUNOJOYO', 'JL. DANAU TOBA NO.24 RT. 1 RW.2 RT 0 RW 0 Tegal Gede Kode Pos 68126', 'Sumbersari', 'Swasta'),
(NULL, 'SMKS DARUL FALAH', 'JL. CURAH UDANG NO.05 BESUK RT 2 RW 12 Wirowongso Kode Pos 68175', 'Ajung', 'Swasta'),
(NULL, 'SMKS PUGER PUGER', 'JL. KENCONG NO. 117 KASIYAN TIMUR RT 0 RW 0 Kasiyan Timur Kode Pos 68164', 'Puger', 'Swasta'),
(NULL, 'SMKS ABDUL AZIZ', 'JL KAKAK TUA NO 17 RT 15 RW 5 Curahlele Kode Pos 68161', 'Balung', 'Swasta'),
(NULL, 'SMKS ASTRA NAWA', 'JL. PAYANGAN SUMBEREJO AMBULU JEMBER RT 3 RW 24 Sumberrejo Kode Pos 68172', 'Ambulu', 'Swasta'),
(NULL, 'SMK ISLAM DARUL MUTA`ALLIMIN', 'Jl. Cumedak Sumbercanting RT 8 RW 2 Cumedak Kode Pos 68195', 'Sumberjambe', 'Swasta'),
(NULL, 'SMKS AL MAJIDI', 'JL. KRAJAN SELODAKON RT 1 RW 7 Selodakon Kode Pos 68155', 'Tanggul', 'Swasta'),
(NULL, 'SMKS ISLAM DARUL HIDAYAH', 'JL. CILIWUNG NO.82 GAMBIRONO RT 3 RW 8 Gambirono Kode Pos 68154', 'Bangsalsari', 'Swasta'),
(NULL, 'SMKS AL-QODIRI', 'JL. MANGGAR 139 A GEBANG - PATRANG RT 2 RW 14 Gebang Kode Pos 68117', 'Patrang', 'Swasta'),
(NULL, 'SMKS 1 BUSTANUL ULUM WULUHAN', 'Jl. Seruni No. 03 RT 2 RW 1 Dukuh Dempok Kode Pos 68162', 'Wuluhan', 'Swasta'),
(NULL, 'SMK MAMBA`UL KHOIRIYATIL ISLAMIYAH', 'JL. BALUNG NO.27 RT 1 RW 2 Bangsalsari Kode Pos 68154', 'Bangsalsari', 'Swasta'),
(NULL, 'SMKS TEKNOLOGI BALUNG', 'RAMBIPUJI NO.33 RT 1 RW 3 Balung Lor Kode Pos 68161', 'Balung', 'Swasta'),
(NULL, 'SMKS DARUL ULUM AS SURUR', 'JL SUMBERJAMBE NO. 09 DUSUN SUMBERBALIN RT 1 RW 1 Cumedak Kode Pos 68195', 'Sumberjambe', 'Swasta'),
(NULL, 'SMKS MUHAMMADIYAH 02 PALERAN', 'Jl. Gambirono, No. 02, Dusun Krajan Wetan, RT. 001, RW. 003 RT 1 RW 3 Paleran Kode Pos 68166', 'Umbulsari', 'Swasta'),
(NULL, 'SMKS MAQNAUL ULUM', 'DS. SUKOREJO - SUKOWONO RT 2 RW 2 Sukorejo Kode Pos 68194', 'Sukowono', 'Swasta'),
(NULL, 'SMKS AL HASAN', 'JL TEROPONG BINTANG NO 1 & 2 RT 1 RW 1 Kemiri Kode Pos 68153', 'Panti', 'Swasta'),
(NULL, 'SMKS ASSALAM SUMBERBARU', 'JL. GERILYA NO.21 SUMBERBARU RT 0 RW 0 Karang Bayat Kode Pos 68156', 'Sumberbaru', 'Swasta'),
(NULL, 'SMKS AL IKHWANIYAH', 'JL KYAI IKHWANUDIN N0 01 RT 3 RW 11 Karangrejo Kode Pos 68165', 'Gumuk Mas', 'Swasta'),
(NULL, 'SMKS NURUL JADID', 'Jl. KH. Salim No. 99 RT 3 RW 3 Sumber Wringin Kode Pos 68194', 'Sukowono', 'Swasta'),
(NULL, 'SMKS HIDAYATUL MUBTADIIN', 'JL. KOTTA BLATER GG.III/160. DESA SIDODADI KEC. TEMPUREJO RT 5 RW 2 Sidodadi Kode Pos 68173', 'Tempurejo', 'Swasta'),
(NULL, 'SMKS ADDIMYATI JENGGAWAH', 'JL. A. YANI NO. 164. PONDOK LALANG RT 0 RW 0 Wonojati Kode Pos 68171', 'Jenggawah', 'Swasta'),
(NULL, 'SMKS NURUL CHOTIB', 'JL. GUNTAR NO.16 WRINGINAGUNG RT 1 RW 21 Wringin Agung Kode Pos 68168', 'Jombang', 'Swasta'),
(NULL, 'SMKS PGRI 5 JEMBER', 'JL. KRAKATAU NO. 60 RT 0 RW 0 Kencong Kode Pos 68167', 'Kencong', 'Swasta'),
(NULL, 'SMKS BAITURROHMAH', 'JL. GUNTAR NO.55 WRINGIN AGUNG RT 3 RW 11 Wringin Agung Kode Pos 68168', 'Jombang', 'Swasta'),
(NULL, 'SMKS AKBAR UMBULSARI', 'JL. PB. SUDIRMAN NO. 50 GUNUNGSARI RT 1 RW 6 Gunungsari Kode Pos 68166', 'Umbulsari', 'Swasta'),
(NULL, 'SMKS ISLAM ASH SHUUFIYAH KENCONG', 'JL. KH. ABD. KHOLIK NO.15 KENCONG RT 1 RW 4 Kencong Kode Pos 68167', 'Kencong', 'Swasta'),
(NULL, 'SMKS TEKNOLOGI PERTANIAN', 'JL. H. HASAN NO.03 RT 1 RW 1 Tugusari Kode Pos 68154', 'Bangsalsari', 'Swasta'),
(NULL, 'SMKS NURUN NAJAH', 'JL. BUKIT PETUNG NO. 16 RT 2 RW 7 Arjasa Kode Pos 68194', 'Sukowono', 'Swasta'),
(NULL, 'SMKS PLUS AL MUJAHIDI TEMBOKREJO', 'JL. GAJAH MADA NO. 04 RT 2 RW 16 Tembokrejo Kode Pos 68165', 'Gumuk Mas', 'Swasta'),
(NULL, 'SMKS RAUDLATUTH THOLABAH', 'JALAN BALUNG KEBONSADENG RT 4 RW 2 Kemuning Sari Kidul Kode Pos 68171', 'Jenggawah', 'Swasta'),
(NULL, 'SMKS BAITURROHMAN', 'Dusun Gumuk Gebang RT 40 RW 24 Nogosari Kode Pos 68152', 'Rambipuji', 'Swasta'),
(NULL, 'SMKS NURINA', 'JL. KAMBOJA NO.01 BANGSALSARI RT 0 RW 0 Bangsalsari Kode Pos 68154', 'Bangsalsari', 'Swasta'),
(NULL, 'SMKS TEKNOLOGI BAITUL MUMININ', 'JL. KH. ACHMAD SYAMSUL ARIFIN NO. 1 CURAHKALONG BANGSALSARI RT 1 RW 4 Curah Kalong Kode Pos 68154', 'Bangsalsari', 'Swasta'),
(NULL, 'SMKS NURUZ ZAMAN', 'DUSUN BANJARSARI RT 03 RW 04 RT 3 RW 10 Gunungsari Kode Pos 68166', 'Umbulsari', 'Swasta'),
(NULL, 'SMKS AL - ISHLAH', 'JL PTP. NUSANTARA XII NO.03 RT 2 RW 2 Sukamakmur Kode Pos 68175', 'Ajung', 'Swasta'),
(NULL, 'SMKS AL MUIEN', 'Jl PESANTREN NO. 11 PLALANGAN RT 1 RW 2 Glagahwero Kode Pos 68153', 'Panti', 'Swasta'),
(NULL, 'SMKS ROUDLATUL ISLAM ARJASA', 'JL. HIMALAYA NO. 57 KEMUNING LOR ARJASA RT 1 RW 3 Kemuningllor Kode Pos 68191', 'Arjasa', 'Swasta'),
(NULL, 'SMKS MUHAMMADIYAH 04 KALISAT', 'JL SEMERU 12 RT 0 RW 0 Kalisat Kode Pos 68193', 'Kalisat', 'Swasta'),
(NULL, 'SMKS AL MASRUROH', 'JL. MOCH SEROEJI NO.16 RT 3 RW 8 Kasiyan Timur Kode Pos 68164', 'Puger', 'Swasta'),
(NULL, 'SMKS MAARIF NU KENCONG', 'Jl. KH. Abdul Kholiq No. 26 RT 1 RW 4 Kencong Kode Pos 68167', 'Kencong', 'Swasta'),
(NULL, 'SMKS AL ISHAQI', 'JL. MERAPI 46 TISNOGAMBAR BANGSALSARI RT 1 RW 1 Tisnogambar Kode Pos 68154', 'Bangsalsari', 'Swasta'),
(NULL, 'SMKS PGRI 3 TANGGUL', 'SEMBORO NO.79 RT 0 RW 0 Tanggul Kulon Kode Pos 68155', 'Tanggul', 'Swasta'),
(NULL, 'SMKS DARUL MUQOMAH', 'JL. SULTAN AGUNG NO. 2-4 RT 2 RW 2 Purwoasri Kode Pos 68165', 'Gumuk Mas', 'Swasta'),
(NULL, 'SMKS BAHRUL ULUM', 'JL BANYUWANGI N0 06 RT 1 RW 2 Sumber Kejayan Kode Pos 68182', 'Mayang', 'Swasta'),
(NULL, 'SMKS AL HIDAYAH', 'JL PESANTREN N0 10 RT 5 RW 17 Tamansari Kode Pos 68162', 'Wuluhan', 'Swasta'),
(NULL, 'SMKS 08 MA ARIF NU', 'JL. KH. ZUHDI ZAIN NO.197 RT 0 RW 0 Ampel Kode Pos 68162', 'Wuluhan', 'Swasta'),
(NULL, 'SMKS PLUS AL AZIZ', 'JL. MERAK 42 RT 0 RW 0 Slawu Kode Pos 68116', 'Patrang', 'Swasta'),
(NULL, 'SMKS PLUS DARUSSALAM BANGSALSARI', 'JL. PROYEK UPCA TISNOGAMBAR RT 2 RW 3 Tisnogambar Kode Pos 68154', 'Bangsalsari', 'Swasta'),
(NULL, 'SMKS GHANIYATUL ULUM', 'Dusun Lamparan Kertosari Pakusari RT 13 RW 4 Kertosari Kode Pos 68181', 'Pakusari', 'Swasta'),
(NULL, 'SMK PENERBANGAN JEMBER', 'Jl. KH. Ahmad Dahlan No.134 RT 1 RW 2 Wonojati Kode Pos 68171', 'Jenggawah', 'Swasta'),
(NULL, 'SMKS MUHAMMADIYAH 5', 'JL. Igir-igir Rowogempol RT 1 RW 8 Cakru Kode Pos 68167', 'Kencong', 'Swasta'),
(NULL, 'SMKS AS-SYAFII', 'DSN. GUMUKSARI DS. NOGOSARI RT 2 RW 4 Nogosari Kode Pos 68152', 'Rambipuji', 'Swasta'),
(3, 'SMKN 2 JEMBER', 'JL. TAWANGMANGU 59 RT 0 RW 0 Tegal Gede Kode Pos 68126', 'Sumbersari', 'Negeri'),
(NULL, 'SMKN 6 JEMBER', 'JL. PB. SUDIRMAN NO. 114 TANGGUL-JEMBER RT 1 RW 18 Tanggul Kulon Kode Pos 68155', 'Tanggul', 'Negeri'),
(NULL, 'SMKS DR. SOEBANDI', 'Jl. dr. Subandi No. 99 RT 1 RW 1 Patrang Kode Pos 68111', 'Patrang', 'Swasta'),
(NULL, 'SMKS ANALIS KESEHATAN JEMBER', 'JL. KACA PIRING NO. 23 GEBANG JEMBER RT 4 RW 1 Gebang Kode Pos 68131', 'Patrang', 'Swasta'),
(NULL, 'SMKS PGRI 4 TANGGUL', 'JL. PB. SUDIRMAN NO. 48 RT 12 RW 3 Tanggul Kulon Kode Pos 68155', 'Tanggul', 'Swasta'),
(NULL, 'SMKS BUSTANUL ULUM', 'Jl. Sholehuddin No. 11 RT 9 RW 3 Karang Semanding Kode Pos 68161', 'Balung', 'Swasta'),
(NULL, 'SMKS MIFTAHUL ULUM', 'JL. R Sosro Prawiro Renes Wirowongso Ajung RT 2 RW 4 Wirowongso Kode Pos 68175', 'Ajung', 'Swasta'),
(NULL, 'SMKS TUNAS BANGSA', 'MANGARAN SUKAMAKMUR AJUNG RT 2 RW 2 Sukamakmur Kode Pos 68175', 'Ajung', 'Swasta');

-- Data tahunan contoh
INSERT INTO data_tahunan (id_anggota_fbkk, tahun, jumlah_lulusan, lanjut_bekerja, kuliah, wirausaha, belum_bekerja, jumlah_mitra, tanda_daftar_bkk) VALUES
(82, 2023, 120, 70, 30, 10, 10, 15, 1),
(82, 2024, 135, 80, 25, 15, 15, 18, 1),
(169, 2024, 95, 55, 20, 12, 8, 10, 1);

-- Informasi publik
INSERT INTO informasi (judul, deskripsi, file_path, is_published) VALUES
('Sosialisasi BKK Tahun 2025', 'Kegiatan sosialisasi program Bursa Kerja Khusus untuk seluruh anggota FBKK Kabupaten Jember.', NULL, 1),
('Lowongan Kerja Mitra Industri', 'Informasi lowongan kerja dari perusahaan mitra BKK di wilayah Jember dan sekitarnya.', NULL, 1),
('Jadwal Pelatihan K3', 'Pelatihan Keselamatan dan Kesehatan Kerja untuk siswa kelas XII.', NULL, 1);